language: node_js
node_js:
  - '9'
  - '10'
env:
  - CI=true
cache: yarn
git:
  depth: 5
script:
  - yarn test -- --runInBand --no-cache --coverage && yarn size
deploy:
  provider: script
  script: curl -X POST -d '' $NETLIFY_BUILD_HOOK
  skip_cleanup: true
  on:
    branch: master