# Automatically label PRs every hour based on your .github/labels.yaml:
#
# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler/blob/master/README.md

name: 'Label PRs from globs'
on:
  schedule:
    - cron: '0 * * * *'

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Label PRs
        uses: jpmcb/prow-github-actions@v1.0.0
        with:
          jobs: 'pr-labeler'
          github-token: '${{ secrets.GITHUB_TOKEN }}'
